-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. USERS (Profiles)
-- Extends the default auth.users
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  role text check (role in ('admin', 'professional', 'patient')),
  phone text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Public profiles are viewable by everyone (for professionals), editable by self
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone" on public.profiles for select using (true);
create policy "Users can insert their own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- 2. SERVICES
create table public.services (
  id serial primary key,
  name text not null,
  category text,
  duration int not null, -- in minutes
  price numeric not null,
  price_range text,
  icon text,
  description text,
  intro text,
  long_description text,
  products text[],
  benefits text[],
  active boolean default true
);

alter table public.services enable row level security;
create policy "Services are viewable by everyone" on public.services for select using (true);

-- 3. PROFESSIONALS
create table public.professionals (
  id serial primary key,
  user_id uuid references public.profiles(id), -- Optional link to a real user
  name text not null,
  specialty text,
  image_url text,
  service_ids int[], -- Array of service IDs they perform
  active boolean default true
);

alter table public.professionals enable row level security;
create policy "Professionals are viewable by everyone" on public.professionals for select using (true);

-- 4. BOOKINGS
create table public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date not null,
  time time not null,
  service_id int references public.services(id),
  professional_id int references public.professionals(id),
  client_id uuid references public.profiles(id), -- The user who booked
  patient_name text, -- For display (snapshot)
  client_email text, -- For display (snapshot)
  status text default 'confirmed' check (status in ('confirmed', 'cancelled', 'completed', 'pending'))
);

alter table public.bookings enable row level security;
-- Policy: Users can see their own bookings. Admins/Profs can see all (simplified for demo).
-- For this prototype, we'll allow public insert to make registration easier, but in production strictly authenticated.
create policy "Users can see own bookings" on public.bookings for select using (auth.uid() = client_id);
create policy "Everyone can insert bookings" on public.bookings for insert with check (true); 

-- 5. VISITS (Financial History)
create table public.visits (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.bookings(id),
  date date not null,
  treatment text,
  professional_name text,
  amount numeric,
  payment_method text,
  patient_id uuid references public.profiles(id)
);

alter table public.visits enable row level security;
create policy "Users see own visits" on public.visits for select using (auth.uid() = patient_id);

-- SEED DATA: SERVICES (From script.js)
INSERT INTO public.services (name, category, duration, price, price_range, icon, description, intro, long_description, products, benefits) VALUES
('Limpieza Facial Profunda', 'Facial', 15, 50, '$40 - $60', 'sparkles', 'Tratamiento revitalizante para una piel radiante.', 'Ideal para purificar tu piel y devolverle su luminosidad natural.', 'Nuestro tratamiento de Limpieza Facial Profunda combina técnicas manuales y aparatología...', ARRAY['Gel Limpiador', 'Peeling Enzimático'], ARRAY['Elimina impurezas', 'Piel suave']),
('Masaje Relajante', 'Corporal', 60, 40, '$35 - $55', 'sun', 'Alivia el estrés y relaja tus músculos.', 'Desconecta del mundo y regálate paz.', 'Experimenta una relajación total con nuestro Masaje Relajante...', ARRAY['Aceite de Almendras', 'Esencia de Lavanda'], ARRAY['Reduce estrés', 'Alivia dolores']),
('Tratamiento Anti-Edad', 'Facial', 30, 80, '$70 - $100', 'gem', 'Tecnología avanzada para rejuvenecer tu piel.', 'Combate los signos del envejecimiento.', 'Nuestro Tratamiento Anti-Edad es un protocolo intensivo...', ARRAY['Gel Conductor', 'Radiofrecuencia'], ARRAY['Reduce líneas', 'Firmeza']),
('Manicura y Pedicura Spa', 'Manos y Pies', 90, 55, '$45 - $65', 'heart', 'Cuidado completo para manos y pies.', 'Mima tus manos con nuestro spa.', 'Más que una manicura, una experiencia de spa...', ARRAY['Sales Minerales', 'Exfoliante'], ARRAY['Uñas cuidadas', 'Relajación']),
('Drenaje Linfático', 'Corporal', 50, 45, '$40 - $50', 'droplets', 'Masaje suave para mejorar la circulación.', 'Elimina toxinas y reduce retención.', 'El Drenaje Linfático Manual es una técnica terapéutica...', ARRAY['Emulsión Drenante'], ARRAY['Mejora circulación', 'Reduce hinchazón']),
('Peeling Químico', 'Facial', 40, 70, '$60 - $80', 'sparkles', 'Renovación celular profunda.', 'Piel nueva, suave y libre de manchas.', 'Transforma la textura de tu piel con nuestro Peeling...', ARRAY['Ácido Glicólico'], ARRAY['Elimina manchas', 'Unifica tono']),
('Maderoterapia', 'Corporal', 60, 50, '$45 - $60', 'tree-deciduous', 'Técnica milenaria para tonificar.', 'Remodela tu figura con madera.', 'La Maderoterapia ayuda a romper depósitos de grasa...', ARRAY['Aceites', 'Kit Maderas'], ARRAY['Tonifica', 'Reduce celulitis']),
('Lifting de Pestañas', 'Facial', 45, 35, '$30 - $45', 'eye', 'Realza tu mirada naturalmente.', 'Pestañas más largas y curvadas.', '', ARRAY[]::text[], ARRAY['Mirada abierta', 'Efecto natural']);

-- SEED DATA: PROFESSIONALS
INSERT INTO public.professionals (name, specialty, image_url, service_ids) VALUES
('Dra. Morcilla', 'Faciales', 'assets/morci.jpeg', ARRAY[1, 3, 6, 8]),
('Lic. Delfi', 'Corporal', 'assets/delfi.jpeg', ARRAY[2, 5, 7]),
('Caro', 'Uñas', 'assets/caro.jpeg', ARRAY[4]);
